version: '3.8'

services:

  app:
    build: .
    image: app/nest
    ports:
      - '3000:3000'
      - '9229:9229'
    tty: true
    volumes:
      - ./:/app


volumes:
  minio_data:
    driver: local
  persistent:
