version: '3.8'

services:

  app:
    build: .
    image: app/nest
    ports:
      - '3000:3000'
      - '9229:9229'
    tty: true
    volumes:
      - ./:/app



  db:
    image: mysql:5.7
    ports: 
        - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_DATABASE: ${DB}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
        - persistent:/var/lib/mysql
    networks:
        - default
  adminer:
      image: adminer
      ports:
      - 8090:8080
     
      networks:
          - default


volumes:
  minio_data:
    driver: local
  persistent:
